version: '2'
services:
  database:
    container_name: dhis2-database
    image: pgracio/dhis2-db:${DB_TAG}
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      PG_DATA: /var/lib/postgresql/data/pgdata
  web:
    container_name: dhis2-web
    image: dhis2/dhis2-web:${WEB_TAG}
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms2048m"
    links:
      - database
    ports:
      - "8085:8080"
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140
  api-tests:
    container_name: dhis2-api-tests
    build: .
    image: dhis2/dhis2-api-tests
    environment:
      DHIS_HOST: web
      DHIS_PORT: 8080
    links:
      - web
    depends_on:
      - web
    entrypoint: dockerize -wait http://web:8080 -timeout 10m